
GET http://dockerdev.agricolus.com:1026/v2/entities?options=keyValues HTTP/1.1
Accept: application/json
fiware-service: agri_contractor_gateway
fiware-servicepath: /

###
POST http://dockerdev.agricolus.com:1026/v2/entities?options=keyValues HTTP/1.1
Accept: application/json
fiware-service: agri_contractor_gateway
fiware-servicepath: /
Content-Type: application/json

{
    "id":"A07022bd-f64f-45af-8262-c6ea03f9d4fa",
    "externalId":"582183",
    "userId":"bd8a4707-df0a-41a7-9223-5f928d27f687",
    "producerCode":"johndeere",
    "lat":51.48961111111111,
    "lng":-0.9416944444444444,
    "name":"6215R (OE19UFA) Coppid",
    "model":"6215R",
    "code":"L 08PE4",
    "type":"tractor",
    "description":"Two-wheel Drive Tractors - 140 Hp And Above",
    "producerCommercialName":"JOHN DEERE",
    "pTime":"2020-11-27T14:57:59Z"
}